### ISSUE TITLE
跳过

### ISSUE THREAD

**Issue by chenzy0355** [h2so0o4/Admin_Intruder#1]
这种方法可以跳过错误次数过多被拉黑吗？

**Comment by h2so0o4** [comment]
测试用的字典是100条，没有被拉黑

**Comment by chenzy0355** [comment]
我下载了您加密过的字典，现在可以直接在Intruder模式里面破解吗？ 不需要encrypt.js了吧

**Comment by h2so0o4** [comment]
encrypt.js和.py这两个是生成字典用的，按理来说如果用加密过的字典，就不用在生成字典。
保险起见最好再生成一次

**Comment by chenzy0355** [comment]
感谢您，如果想请您指导一下，可以给个价格吗

**Comment by h2so0o4** [comment]
> 感谢您，如果想请您指导一下，可以给个价格吗

尽量免费给你解答吧

**Comment by chenzy0355** [comment]
我现在就差一份字典了，还有py环境的安装，不过爆破的时候有显示502的是什么意思

**Comment by h2so0o4** [comment]
1、字典可以百度搜索下猪猪侠字典，我认为这个比较齐全
2、py环境建议自己安装，因为会经常用到，自己装留个印象
3、502大概率是线程调的比较高，把burp的线程调低一些
![image](https://user-images.githubusercontent.com/49434585/132124421-c41184d5-9492-4760-806c-ce3ffd19b204.png)
4、我刚刚又测试了一遍，改动了一部分代码，是仍然可以爆破成功的
![image](https://user-images.githubusercontent.com/49434585/132124280-822b9158-4231-4b61-8317-66d1af97bc0c.png)

**Comment by chenzy0355** [comment]
我用的pycharm，库已经导入了，现在运行报错
![7a2609fae8a2bf32](https://user-images.githubusercontent.com/38786378/132125176-dc256798-89e0-4fbb-b56b-136bcae22c57.png)
对了，我是把那个js调用.py复制粘贴到main.py了。

**Comment by chenzy0355** [comment]
之前是我直接全部复制了，现在用了最新版本，运行直接显示图二，不过并没有写入加密后的东西。
![} 4X@7 M%CMGO6K85 HRN 9](https://user-images.githubusercontent.com/38786378/132126604-587bc176-4b0d-42d1-86a9-232b3c6b8eb2.png)
![DA$TWV%F)K9{E7{KE3UX(T7](https://user-images.githubusercontent.com/38786378/132126608-28d7eb3b-d1e7-443c-adcb-413e190130a9.png)
![Uploading @7CVTQZQVNGNPQ5GXW71U3P.png…]()

**Comment by h2so0o4** [comment]
> 之前是我直接全部复制了，现在用了最新版本，运行直接显示图二，不过并没有写入加密后的东西。

我这边跑没问题哦，你自己debug一下，检查每一步输出是否正常

**Comment by chenzy0355** [comment]
我把最后一行creative_book()删了就不会报错，但是不会写出加密后的东西

**Comment by h2so0o4** [comment]
> 之前是我直接全部复制了，现在用了最新版本，运行直接显示图二，不过并没有写入加密后的东西。

看起来JS调用.py这个文件不在你项目的文件夹里，这是很基础的的python问题哦，要先磨练一下基础

**Comment by Chen6668** [comment]
终于好了，我这里只有debug才能运行成功。
![Uploading IMG_20210905_204653.jpg…]()

**Comment by Chen6668** [comment]
老哥，我这个code字段为0，是成功了吧？如果成功了，我怎么转换回来，知道他原来是哪一个？
![Uploading 0U6IVCN%~8%VCPC62CS9$ZA(1).jpg…]()
